name: release

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup

    - name: build
      run: cargo build --release

    # sanity
    - run: |
        if ! test -f target/wasm32-wasi/release/proxy_wasm_rust_response_transformer.wasm; then
          echo "missing output binary"
          exit 1
        fi

    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'target/wasm32-wasi/release/proxy_wasm_rust_response_transformer.wasm'
        draft: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
