name: release

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest
    needs: test # don't release unless tests are all passing
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup

    - name: build
      run: cargo build --release

    - run: |
        if ! test -f target/wasm32-wasi/release/proxy_wasm_rust_response_transformer.wasm; then
          echo "missing output binary"
          exit 1
        fi
        cp target/wasm32-wasi/release/proxy_wasm_rust_response_transformer.wasm filter.wasm

    - uses: ncipollo/release-action@v1
      with:
        artifacts: filter.wasm,filter.meta.json
        draft: ${{ github.ref != 'refs/heads/main' && 'true' || 'false' }}
        prerelease: ${{ github.ref != 'refs/heads/main' && 'true' || 'false' }}
