name: test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

  workflow_call:

defaults:
  run:
    shell: bash

# cancel previous runs if new commits are pushed to the PR, but run for each commit on master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          build: true

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - uses: actions-rs/cargo@v1
        with:
          command: check

  rustfmt:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: rustup component add clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings
